// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qggykabklxvnibfjjldf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnZ3lrYWJrbHh2bmliZmpqbGRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI4NjY2NTQsImV4cCI6MjA3ODQ0MjY1NH0.LgrY7HL_-Al9I85tuIwZPpd-No1mKijdqS1SubM1GlU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});